# Generated by Django 3.0.1 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20200426_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='education',
            field=models.CharField(default='mba', max_length=120),
            preserve_default=False,
        ),
    ]
