# Generated by Django 3.0.1 on 2020-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_job_post_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='job_post',
            name='deadline',
            field=models.CharField(default='12-03-2020', max_length=10),
            preserve_default=False,
        ),
    ]
