# Generated by Django 3.0.1 on 2020-04-26 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20200426_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='experience',
            field=models.CharField(choices=[('NO', 'No'), ('ON', '1 year'), ('TW', '2 years'), ('TH', '3 years'), ('FV', '5 years'), ('TN', '10 years'), ('AT', 'Above 10 years')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='job_post',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
