# Generated by Django 3.0.1 on 2020-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_job_apply_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter_register',
            name='company_description',
            field=models.TextField(default='Write something about your company.'),
        ),
    ]
