# Generated by Django 3.0.1 on 2020-04-28 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_recruiter_register_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
