# Generated by Django 3.0.1 on 2020-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_job_post_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='deadline',
            field=models.DateField(),
        ),
    ]
