# Generated by Django 3.0.1 on 2020-04-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20200428_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='deadline',
            field=models.CharField(max_length=10),
        ),
    ]
