# Generated by Django 3.0.1 on 2020-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_job_post_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='deadline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
