# Generated by Django 3.0.1 on 2020-04-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_auto_20200428_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
