# Generated by Django 3.0.1 on 2020-04-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_auto_20200428_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='deadline',
        ),
    ]
