# Generated by Django 3.0.1 on 2020-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_job_post_prefered_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='prefered_Division',
            field=models.CharField(choices=[('DH', 'Dhaka'), ('RH', 'Rajshahi'), ('BR', 'Borishal'), ('KH', 'Khulna'), ('SY', 'Shylet'), ('KM', 'Kumilla'), ('RR', 'Rongpur')], default=1, max_length=2),
        ),
    ]
