# Generated by Django 3.0.1 on 2020-04-29 03:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_job_post_prefered_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
