# Generated by Django 3.0.1 on 2020-04-29 06:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20200429_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter_register',
            name='company_description',
            field=ckeditor.fields.RichTextField(default='Our company is provide good services.'),
        ),
    ]
