# Generated by Django 3.0.1 on 2020-04-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_auto_20200430_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_register',
            name='about_me',
            field=models.TextField(default='I am a Job Seeker.'),
        ),
        migrations.AddField(
            model_name='job_seeker_register',
            name='current_Adrress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker_register',
            name='parmanant_Adrress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker_register',
            name='picture',
            field=models.FileField(default='profile.jpg', upload_to=''),
        ),
    ]
