# Generated by Django 3.0.1 on 2020-05-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_our_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Our_Post',
            new_name='Blog_Post',
        ),
    ]
