# Generated by Django 3.0.1 on 2020-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_auto_20200617_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_register',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recruiter_register',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
