# Generated by Django 3.0.1 on 2020-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_auto_20200617_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter_register',
            name='company_description',
            field=models.TextField(),
        ),
    ]
