# Generated by Django 3.0.1 on 2020-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_auto_20200617_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_register',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
