# Generated by Django 3.0.1 on 2020-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_auto_20200630_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_description',
            field=models.TextField(),
        ),
    ]
