# Generated by Django 3.0.1 on 2020-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_auto_20200630_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='prefered_Division',
            field=models.CharField(choices=[('AW', 'Any Where'), ('DH', 'Dhaka'), ('RH', 'Rajshahi'), ('BR', 'Borishal'), ('KH', 'Khulna'), ('SY', 'Shylet'), ('KM', 'Kumilla'), ('RR', 'Rongpur')], default=1, max_length=2),
        ),
    ]
