# Generated by Django 3.0.1 on 2020-07-06 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_auto_20200630_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply',
            name='job_recruiter_email',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='job_seeker_email',
        ),
        migrations.RemoveField(
            model_name='job_apply',
            name='title',
        ),
        migrations.AddField(
            model_name='job_apply',
            name='job',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job_Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_apply',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job_Seeker_Register'),
            preserve_default=False,
        ),
    ]
