# Generated by Django 3.0.1 on 2020-07-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_notificationforrecruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='recruiter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Recruiter_Register'),
            preserve_default=False,
        ),
    ]
