# Generated by Django 3.0.1 on 2020-07-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_create_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_interview',
            options={'verbose_name': 'Create Interview', 'verbose_name_plural': 'Create Interviews'},
        ),
        migrations.RemoveField(
            model_name='create_interview',
            name='is_view',
        ),
        migrations.CreateModel(
            name='Interview_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_view', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job_Post')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job_Seeker_Register')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Recruiter_Register')),
            ],
            options={
                'verbose_name': 'Create Interview',
                'verbose_name_plural': 'Create Interviews',
            },
        ),
    ]
