# Generated by Django 3.0.1 on 2020-07-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0036_auto_20200707_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview_notification',
            options={'verbose_name': 'Interview Notification', 'verbose_name_plural': 'Interview Notifications'},
        ),
        migrations.RemoveField(
            model_name='interview_notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='interview_notification',
            name='recruiter',
        ),
    ]
