# Generated by Django 3.0.1 on 2020-07-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0037_auto_20200707_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_interview',
            name='jobseeker',
        ),
    ]
