# Generated by Django 3.0.1 on 2020-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0040_interview_notification_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationforrecruiter',
            options={'verbose_name': 'Job Apply Notification', 'verbose_name_plural': 'Job Apply Notifications'},
        ),
        migrations.RenameField(
            model_name='recruiter_register',
            old_name='full_name',
            new_name='company_url',
        ),
        migrations.AddField(
            model_name='recruiter_register',
            name='company_location',
            field=models.TextField(default='dhaka'),
            preserve_default=False,
        ),
    ]
