# Generated by Django 3.0.1 on 2020-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0042_auto_20200708_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_register',
            name='picture',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
    ]
