# Generated by Django 3.0.1 on 2020-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0043_auto_20200708_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_register',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
