# Generated by Django 3.0.1 on 2020-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0045_auto_20200709_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_register',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
