# Generated by Django 3.0.1 on 2020-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0050_auto_20200709_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='exam_name',
            field=models.CharField(choices=[('SS', 'SSC or Equivalent'), ('HS', 'HSC or Equivalent'), ('OR', 'Onars or Equivalent'), ('MS', 'Master or Equivalent'), ('BS', 'BSC'), ('MS', 'MSC'), ('BB', 'BBA'), ('DP', 'Diploma'), ('OT', 'Others')], default=1, max_length=2),
        ),
    ]
