# Generated by Django 3.0.1 on 2020-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0051_auto_20200710_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='cgpa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='duration',
            field=models.CharField(default='4 years', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='major',
            field=models.CharField(choices=[('CM', 'Commerce'), ('AT', 'Atrs'), ('SC', 'Science'), ('CS', 'CSE'), ('EE', 'EEE'), ('OT', 'Others')], default=1, max_length=2),
        ),
    ]
