# Generated by Django 3.0.1 on 2020-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0052_auto_20200710_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_cv_academic_qualification',
            options={'verbose_name': 'CV Academic Qualification', 'verbose_name_plural': 'CV Academic Qualifications'},
        ),
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='exam_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='major',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='passing_year',
            field=models.CharField(max_length=10),
        ),
    ]
