# Generated by Django 3.0.1 on 2020-07-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0054_auto_20200710_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cv_academic_qualification',
            name='duration',
            field=models.CharField(blank=True, default='---', max_length=50, null=True),
        ),
    ]
