# Generated by Django 3.0.1 on 2020-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0056_auto_20200710_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_cv_job_experience',
            name='is_still_work',
            field=models.BooleanField(default=False),
        ),
    ]
